### ISSUE TITLE
under what user should we run this ? 

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#1]
should we run it with sudo or the username serverpilot ?

**Comment by dfinnema** [comment]
At this stage it needs to be run as Root / Sudo due to the fact is uses the Lets Encrypt (https://github.com/letsencrypt/letsencrypt) which also requires root privileges.

**Comment by raykai** [comment]
so in ubuntu server we should use sudo -s ?

**Comment by dfinnema** [comment]
Logging in as Root will probably work best
