### ISSUE TITLE
need help getting 2 cert for 1 website

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#14]
im having a hard time understanding how to get 2 cert for one website/app i have 2 domains pointing to the same app EX  test.com test.ca  ca = canada domain both are pointing to the same website. if i try and apply 2 cert it over write the other one. i cant use just one or the cert in the browser will only show that it was meant for ether .com or .ca not both.

**Comment by dfinnema** [comment]
One certificate per IP. You can make one certificate with multiple domains using SNI.

Just make sure you enter both domains when generating the certificate

**Comment by krebbi** [comment]
https://github.com/dfinnema/le-serverpilot/pull/5
