### ISSUE TITLE
missing certificate transparency information

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#15]
the certs are missing some information:
![1](https://cloud.githubusercontent.com/assets/8138894/13388583/26227394-de8f-11e5-9589-963a9789fd1c.JPG)

no way to add info like this : 
![2](https://cloud.githubusercontent.com/assets/8138894/13388605/48313006-de8f-11e5-984d-34f945f44f0a.JPG)

we get say this: 
![3](https://cloud.githubusercontent.com/assets/8138894/13388610/52a73580-de8f-11e5-9d37-fafd71796e12.JPG)

but if we could add certificate transparency information it would show as say this exp: 
![4](https://cloud.githubusercontent.com/assets/8138894/13388616/6ad1eb64-de8f-11e5-886c-9ffb8cc4589c.JPG)

is this normal or is this work in progress ? or maybe its not possible with letsencrypt ?

**Comment by dfinnema** [comment]
That's for an EV Certificate not possible with let's encrypt (https://en.m.wikipedia.org/wiki/Extended_Validation_Certificate)
