### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by coniets** [dfinnema/le-serverpilot#16]
root@server:/etc/le-serverpilot# ./df.sh
/etc/le-serverpilot/config: line 4: syntax error near unexpected token `<<<'
/etc/le-serverpilot/config: line 4: `<<<<<<< HEAD'
./df.sh: line 120: syntax error near unexpected token `<<<'
./df.sh: line 120: `<<<<<<< HEAD'

**Comment by dfinnema** [comment]
Sorry some files got corrupted during a merge, will try and get these fixed asap

**Comment by dfinnema** [comment]
It should now be all fixed, let me know if you encounter any further issues
