### ISSUE TITLE
Cannot reach the Challenge dir

### ISSUE THREAD

**Issue by Remo** [dfinnema/le-serverpilot#19]
When trying to issue a new certificate I get the message below. I wanted two domains, but also tested with just one, doesn't change anything. Any idea what could be wrong?

``` 
 - global auto challange directory exists
 + No changes needed in Vhosts
 + Using config file /root/le-serverpilot/tmp.df
 + Challenge directory found
 + Processing mydomain.com
 + Challenge directory found
 ERROR: Cannot reach the Challenge dir using http (ERROR: 000)
```

**Comment by dfinnema** [comment]
The script will check if it can reach the TMP file in the challenge directory for all domains you are attempting to get a certificate for prior to connecting to Lets Encrypt's servers. Can you reach both challenge directories by http using a browser? (yourdomain.com/.well-known/acme-challenge/df768768.txt)

**Comment by Remo** [comment]
there is no file in that challenge directory and when I try to issue the cert again, it simply says:
   
    Nothing issued/renewed!

**Comment by Remo** [comment]
creating a new cert if the process stopped right in the middle is a bit annoying. Seems like /etc was protected a bit better and I was mislead by the well-known directory in my public folder which I guess was created by an older version of this script.
