### ISSUE TITLE
letsencrypt looking for /letsencrypt/ and not /le-serverpilot/letsencrypt/

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#2]
when i run option 7) Setup the config file. i get a error:
config-lets.sh: line 33: cd: letsencrypt: No such file or directory

when using the option  4) Install Lets Encrypt
it installs letsencrypt in the folder le-serverpilot. but the option 7 is looking for the letsencrypt folder in the home folder as there is a cd on line 32 then a cd letsencrypt on line 33 

on line 32-33 of the config-lets.sh:
line 32: cd
line 33: cd letsencrypt 

so for a workaround i got it working by editing the line 32 by removing the 1st cd 

but im having the same prob with option 1

issue-cert.sh: line 18: cd: letsencrypt: No such file or directory

line 17-18:
    cd
    cd letsencrypt 

so workaround would be to remove the 1st cd 

then im getting a error :
issue-cert.sh: line 54: cd: letsencrypt: No such file or directory
bash: letsencrypt-auto: No such file or directory

a fix could be to change the scrip so it installs letsencrypt in home and not in le-serverpilot folder

**Comment by dfinnema** [comment]
Thank you for your feedback, when I created the scripts I was running them from the home dir hence the first CD. Thanks for the workaround I shall look at updating the scripts to make them a bit more flexible with location in the future. 

Is it all working for you now?

**Comment by raykai** [comment]
i just added on my 1st post on other error 

issue-cert.sh: line 54: cd: letsencrypt: No such file or directory
bash: letsencrypt-auto: No such file or directory

**Comment by raykai** [comment]
changing the install location would fix this as if we manually change the letsencrypt files it will be over overridden when updating letsencrypt...

**Comment by raykai** [comment]
il test it ones u have time to fix the install location 

thx for your work :)

**Comment by statrixbob** [comment]
I changed all instances of 'cd letsencrypt' to 'cd ~/le-serverpilot/letsencrypt' and that seemed to the trick up to the point where I actually tried to activevate. I ended up with a authentication error on public/.well-known. 

It wasn't the permissions, it was the .htaccess directives forbidding any access to a '.' file or directory. I commented that out, restarted apache, did the activation, then removed the comment in .htaccess effectively denying permission again and restarted. Worked fine.

Essentially with just a couple of tweaks I've got SSL on a serverpilot app in DigitalOcean. 

Thanks!

**Comment by raykai** [comment]
statrixbob > can u add the fix to this repository ?

**Comment by dfinnema** [comment]
I have updated the code to use another shell script which should solve the issues you were having earlier

**Comment by raykai** [comment]
il give it a run  tomorrow il post back soon :) thx for the hard work :)
