### ISSUE TITLE
Redirect from alternative domain

### ISSUE THREAD

**Issue by Remo** [dfinnema/le-serverpilot#20]
Is there a chance that we can create a cert for two domains which are part of the same app?

* my-main-domain.com
* my-alternative-domain.com

It can happen that both domains are used with https due to which I must have a cert which is valid for both. Creating a new app just to redirect it, is pretty silly. I know that there's this note:

    > NOTE: you must have these domains in your different vhosts
         for validation otherwise the challenge will fail

Is this a limitation by letsencrypt?

**Comment by dfinnema** [comment]
No as long as you specify the (sub)domain names when creating your certificate it should work. Best way is just to test this in TESTING mode. I have one app running of several domains with LE working

**Comment by Remo** [comment]
Well, tried it on two different servers, doesn't work for me. Whatever I do it won't reach the challenge dir, either with error 000 or 403

**Comment by dfinnema** [comment]
Are you able to reach the challenge directory using your browser after it fails?

 (yourdomain.com/.well-known/acme-challenge/df768768.txt)

**Comment by dfinnema** [comment]
Might be a permission issue, what OS are you running and can you reach the app by http?

**Comment by Remo** [comment]
Does serverpilot support anything beside Ubuntu 14.04 LTS? Yes, the app works perfectly fine.

**Comment by dfinnema** [comment]
Will have a look when I get back Home tonight. (8 AM here).

**Comment by Remo** [comment]
Okay, see other issue, this part I managed to fix. The note is rather confusing though, it doesn't seem to add any kind of value to the process. Can't we just remove that?

**Comment by Remo** [comment]
Or is this the reason why I'm currently seeing `ERR_CERT_COMMON_NAME_INVALID`? I've specified both domains when I created the certificate, but both domains are part of the same app.

**Comment by Remo** [comment]
I think it would be nice to have a note saying that you must add `www` manually.
