### ISSUE TITLE
error removing Cron Job 

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#22]
getting a error when removing a cron job  i renamed my domain to *DOMAIN*

Removing Automation for *DOMAIN*
 + Removed cron.config from *DOMAIN*
"-":0: bad minute
errors in crontab file, can't install.
 + Cron job removed
REMOVAL COMPLETED

**Comment by dfinnema** [comment]
This issue has now been fixed for both the development and master branch
