### ISSUE TITLE
can we get a How to for mail gun

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#24]
i dont know where to get the info for the config file for the mail gun part :

DF_MAIL=0

MAILGUN API
DF_MAIL_API=

MAILGUN DOMAIN
DF_MAIL_DOMAIN=

 EMAIL FROM
DF_MAIL_FROM_NAME=
DF_MAIL_FROM_EMAIL=

 EMAIL TO
DF_MAIL_TO=

i did log in my mailgun but i dont see where to get thos info ...

**Comment by dfinnema** [comment]
I have added a link into the readme on how to get the API key
