### ISSUE TITLE
note missing ? or am i wrong 

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#25]
should there be a not be a note in issue-cert.sh for (NOTE: www.mydomain and mydomain are not the same and need to be") ?

**Comment by dfinnema** [comment]
Its split into two lines


    echo "   NOTE: www.mydomain and mydomain are not the same and need to be"
    echo "         added seperatly using SNI"

**Comment by raykai** [comment]
there is no note in the issue-cert.sh for that its only in the sp-https.sh but dont we create the SNI when using the issue-cert.sh so the note should be there too no ? and not in sp-https.sh as we only enter the primary SNI there no ? or am i mixed up ?

**Comment by dfinnema** [comment]
Thanks for seeing that, I have now updated it to reflect the correct location.
