### ISSUE TITLE
auto renew using crontab

### ISSUE THREAD

**Issue by Remo** [dfinnema/le-serverpilot#3]
Maybe I'm missing something, but I think this needs to run four times a year?
Would it be possible to have a script we can call from a cronjob to renew all certificiates?

**Comment by dfinnema** [comment]
I have added CRON support, its currently being tested in the development branch if you want to test it out already.

**Comment by raykai** [comment]
so is the CRON stable now ?

**Comment by dfinnema** [comment]
Cron support is now stable
