### ISSUE TITLE
bug in development revoke a cert

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#33]
in dummy certificate if i revoke a cert i get a error :

![2](https://cloud.githubusercontent.com/assets/8138894/15203606/5a35fbb0-17d3-11e6-9a85-cc4469f56fd2.JPG)

**Comment by raykai** [comment]
wander how you managed to remove yours when testing for https ...

**Comment by dfinnema** [comment]
Sorry hadn't uploaded the changes in syntax to the development one. Fixed now

**Comment by raykai** [comment]
seams fixed for this one.
will testing with a dummy certificate show https in the address bar ?  never used a test dummy cert before.
