### ISSUE TITLE
nginx restart error

### ISSUE THREAD

**Issue by krebbi** [dfinnema/le-serverpilot#4]
After issuing a cert for the second app I get 

Restarting nginx-sp: nginx: [warn] conflicting server name "$server_name" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "$server_name" on [::]:80, ignored
nginx: [warn] conflicting server name "$server_name" on 0.0.0.0:443, ignored
nginx-sp.

when trying to Activate SLL for the App with the new cert.

**Comment by dfinnema** [comment]
Thanks for the issue submit this will be fixed in the next update.
