### ISSUE TITLE
error on issuing a ssl

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#6]
+ Domain Valid
 + Using config file /etc/le-serverpilot/config.sh
acme.sh: line 223: curl: command not found
  ERROR: An error occurred while sending get-request to https://acme-v01.api.letsencrypt.org/directo           ry (Status )

 + Details:
)
acme.sh: line 242: DOMAINS_TXT: unbound variable

**Comment by krebbi** [comment]
so I guess this is fixed as well?
