### ISSUE TITLE
error on entering email in account management

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#7]
+ Using config file /etc/le-serverpilot/tmp.df
/etc/le-serverpilot/acme.sh: line 227: curl: command not found
  ERROR: An error occurred while sending get-request to https://acme-v01.api.letsencrypt.org/directory (Status )

 + Details:
)

**Comment by krebbi** [comment]
what does this command return on your server?

curl -V

**Comment by raykai** [comment]
trying it give me 2 mins

**Comment by raykai** [comment]
bash: curl: command not found
 is curl  not installed serverpilot ?

**Comment by raykai** [comment]
i used sudo apt-get install curl

now when using curl -V i get :
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by raykai** [comment]
hope its the right way to install curl.

its working now only thing i would need help with is in the development branch in the config file i would need more info in setting up the mail gun API what sould go in the DF_MAIL_API line and 
DF_MAIL_DOMAIN= ?

# MAILGUN API
DF_MAIL_API=

# MAILGUN DOMAIN
DF_MAIL_DOMAIN=

# EMAIL FROM
DF_MAIL_FROM_NAME=
DF_MAIL_FROM_EMAIL=

# EMAIL TO
DF_MAIL_TO=

**Comment by krebbi** [comment]
sorry, I don't have any experience with serverpilot, mailgun and let's encrypt. 
and maybe you should open a new issue to keep things separated.

**Comment by raykai** [comment]
thx for the help
