### ISSUE TITLE
Postfix instead of mail gun to send out the emails ?

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#8]
in the development branch in the config file there is the mail gun API would there be a way to use serverpilot that already has Postfix instead of using mail gun to send out the emails ?

see 1st part of this page  https://serverpilot.io/community/articles/guide-to-hosting-email.html
"ServerPilot installs and configures Postfix so your scripts can send email from your server. "

**Comment by dfinnema** [comment]
Happy to include this option, using mailgun just required one CURL command hence why I used it. Feel free to make a postfix option using a pull request
