### ISSUE TITLE
error when revoke SSL Certificate.

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#9]
im getting a error when trying to revoke CERT.

WARNING: This SSL Certificate is currently in use, continue? (y/n)
  - You should issue a new one first
y

Do you wish to revoke 'cert-1456704563.pem' (y/n)?
 > This cannot be undone!
y

 + Attempting to revoke SSL Certificate...
 + Using config file /etc/le-serverpilot/tmp.df
ERROR: Domains could not be loaded

**Comment by raykai** [comment]
i dont see any tmp.df in /etc/le-serverpilot/ folder 

ps:i can see all hidden folders so that's not the prob.

**Comment by dfinnema** [comment]
This has now been fixed in the development branch. The tmp.df file is a temporary file created during running and is removed afterwards.
